[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
medifund = "8r9QQDRiqBqnGiXXAdhsa2acYs35EgH9HMHU2Eb92PTA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
